### ISSUE TITLE
all images return the same feature

### ISSUE THREAD

**Issue by qingchenwuhou** [Laulian/MxNet2Caffe-mobilefacenet#1]
HI, 
Firstly, I check your result is right.
Then, I use your code to convert resnext from mxnet to caffe, but bug occurs that all images return the same features.
I print the first layer's output 'bn_data', the caffe's outputs are same to all images.
I ensure the same preprocess to caffe and mxnet, thus same input into network(checked by print data).
Do you know the reason.
Thanks.

**Comment by Laulian** [comment]
some advice:
1,check yout prototxt file to make sure your net can work
2,print the layer's weights value to check if they were normal
I have not tested on resnet yet,and I will try it,or you can send yout file to me

**Comment by Laulian** [comment]
@qingchenwuhou 
some advice:
1,check yout prototxt file to make sure your net can work
2,print the layer's weights value to check if they were normal
I have not tested on resnet yet,and I will try it,or you can send your file to me

**Comment by Laulian** [comment]
I tried the resnet-50 model from https://pan.baidu.com/s/1mj6X7MK,there is no problem with the result.

**Comment by shiyuanyin** [comment]
@Laulian 
你好，我训练的时候超参数不一样 wd =4e-05 不是作者wd=0.0005，其他超参数好像是一样的，没怎么变化
使用作者的模型，转换是一样的输出，我自己又finutune训练 ,的模型输出就不一样了，请问你有什么建议吗？

**Comment by qingchenwuhou** [comment]
Finally, I realize the accurate conversion from MXNet model to Caffe Model by MMdnn.
  In order to ensure the same preprocess before input into both networks, in verification exp I use the MXNet preprocess and convert mx-NDArray to numpy, then input the 224*224 numpy into caffe network. The process obtains the accurate result. 
  The same preprocess is important in check exp, where formerly I used caffe preprocess by mistake and was confused by the wrong results. And you will find MXNet preprocess contains steps(subtract mean, divide std, imresize realized by opencv not cv2, crop) which are different from Caffe preprocess. So In Caffe prediction code, you should execute the same preprocess.
  The command I use in mmdnn is:

mmtoir -f mxnet -n downed_mxnet_model/resnext-101-symbol.json -w downed_mxnet_model/resnext-101-0000.params -d converted_caffe_model/resnext101 --inputSh    ape 3,224,224
 mmtocode -f caffe -n converted_caffe_model/resnext101.pb -w converted_caffe_model/resnext101.npy -d converted_caffe_model/resnext101_caffe_converted.py -    dw converted_caffe_model/resnext101_caffe_converted.npy
mmtomodel -f caffe -in converted_caffe_model/resnext101_caffe_converted.py -iw converted_caffe_model/resnext101_caffe_converted.npy -o converted_caffe_mo    del/resnext101_final

**Comment by Laulian** [comment]
@shiyuanyin  check the last layer's output of each bottleneck in resnet-50,that is the Eltwise layer.And you will figure out where the difference generated.
